### ISSUE TITLE
naemon 1.1.0

### ISSUE THREAD

**Issue by lidskialf** [statusengine/module#5]
Hi, 

Since naemon 1.1.0 update - naemon doesn't work/start with ``` broker_module=/opt/statusengine/module/statusengine-naemon*.so ``` is it possible to get an update for the new naemon version? 

System: Ubuntu Bionic 18.04

Kind regards,

Lidskialf.

**Comment by nook24** [comment]
Hi @lidskialf,
from [Naemon's changelog](https://github.com/naemon/naemon-core/blob/684c1c680331c8a892fa0d03f8fd816c002237ee/NEWS#L1-L15):
````
* increased CURRENT_NEB_API_VERSION, this means you have to recompile your NEB modules
````

Have you already tried to reinstall the Statusengine Broker? https://statusengine.org/broker/#installation

**Comment by lidskialf** [comment]
Hi @nook24,

Yes i have rebuild the Statusengine Broker with the same result.

## statusengine-naemon.o 
Here the error log output: https://www.nopaste.eu/p?q=d25DZVA

## statusengine-naemon-1-0-5.o
Here the error log output: https://www.nopaste.eu/p?q=TGFhazY

Kind regards,

Lidskialf.

**Comment by nook24** [comment]
Ok this should be a simple one:
```
Error: Module '/opt/statusengine/module/statusengine-naemon-1-0-5.o' is using an old or unspecified version of the event broker API.  Module will be unloaded.
```

I will come back to soon

**Comment by nook24** [comment]
Done. Should be working now.
I also updated the docs at https://github.com/statusengine/docs/pull/6/files and online: https://statusengine.org/broker/#installation

Could you please check if the issue is gone?

**Comment by lidskialf** [comment]
Hi @nook24,

Now it works again. Thanks!

`[ ok ] Starting naemon (via systemctl): naemon.service.`

Kind regards,

Lidskialf.
